kind: Deployment
apiVersion: apps/v1
metadata:
   name: website
   namespace : website
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: website
   template:
      metadata:
        labels:
          app: website
      spec:
       containers:
        - name: website
          image: riqimaruq/belajar
          imagePullPolicy: Always
          ports:
          - containerPort: 80
