apiVersion: v1
kind: Service
metada:
  name: nginx-service
metadata:
  labels:
    app.kubernetes.io/instance: belajar
  namespace: belajar
spec:
  ports:
    - nodePort: 30007
      port: 80
  selector:
    app: nginx
  type: NodePort
