kind: Service                             
apiVersion: v1
metadata:
  name: website
  labels:
    app: website
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: website                    
  type: LoadBalancer                   
