apiVersion: v1
kind: Service
metadata:
  name: app-test-1
  namespace: app-test-1
  labels:
    app: app-test-1
spec:
  type: NodePort
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: app-test-1
